baseURL = "https://bellabeen.github.io"
languageCode = "en-us"
title = "nerdybeen"
disablePathToLower = false

#themesDir = "themes"
theme = "pulp"
# Author's name (appears in meta tags and under posts)
    author = "Muhammad Bella Buay Nunyai"